spring:
  application:
    name: hello-world-api
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sql_helloworld_user?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: Assn199534
server:
  port: 8081